### ISSUE TITLE
Can not get payment URL for online bank debit payments

### ISSUE THREAD

**Issue by andresams** [moip/moip-sdk-php#208]
After creating an order and a payment using online bank debit, there are no method which can be used to return the payment URL.

Thus, if I check the payment object by using print_r(), I am able to find the following URL - which is likely to be what I want - however, it does not works:

> https://webapps-sandbox.moip.com.br/sandbox/ProcessarDebito.do?externalId=PAY-WU9XIWJTMEVX

I wonder if this is a sandbox-only issue or there is no debit payment available for this API version.
Thank you!

**Comment by andresams** [comment]
I have some new info to add.

When I create a payment with Itaú, I get a different URL:

> https://checkout-sandbox.moip.com.br/debit/itau/PAY-KLBOBRG89DDD#

This one works. However, for Bradesco, Banrisul and Banco do Brasil I keep getting the same url pattern as the previous message shows - and none of them work.

**Comment by caiogaspar** [comment]
Hi @andresams, how are you?
Moip have two versions of API: v1 and v2. 
Currently, debit payment with Itaú is available on both versions, but debit payments with Bradesco, Banrisul and Banco do Brasil are only available on v1.
Our SDK is integrated only with v2, that's why the other links don't appear.

Regards!
